### ISSUE TITLE
Timeline: Core.js functions `zoomIn` and `zoomOut` are broken

### ISSUE THREAD

**Issue by milosrs** [visjs/vis-timeline#1642]
I have a React 18 app that is putting the `Timeline()` object into context.
Another component is invoking `timeline.zoomIn()` `timeline.zoomOut()` `timeline.moveTo()` and `timeline.fit()`.

`moveTo()` and `fit()` work just fine.
`zoomIn` and `zoomOut` don't work, and are throwing errors. Error log is below. I have debugged Core.js, and it turns out that `this` object is undefined when invoking these two functions. I am using other functions from Core.js, and `this` object resolves to `Timeline`

Error log:
```
Cannot read properties of undefined (reading 'getWindow')
TypeError: Cannot read properties of undefined (reading 'getWindow')
    at zoomIn (http://localhost:3000/static/js/bundle.js:228266:24)
    at zoomClick (http://localhost:3000/main.cb01a1e6d1b3b1e1c41f.hot-update.js:60:5)
    at onClick (http://localhost:3000/main.cb01a1e6d1b3b1e1c41f.hot-update.js:68:13)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:94459:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:94503:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:94560:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:94574:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:98718:7)
    at processDispatchQueueItemsInOrder (http://localhost:3000/static/js/bundle.js:98744:11)
    at processDispatchQueue (http://localhost:3000/static/js/bundle.js:98755:9)
```

**Comment by milosrs** [comment]
Nevermind, I'm dumb.

I have passed the `timeline.zoomOut` and `timeline.zoomIn` as callbacks to an anonymous function. Probably this is why `this` cant be resolved.
