### ISSUE TITLE
NPM Build Issues

### ISSUE THREAD

**Issue by melloware** [visjs/vis-timeline#419]
**Windows 10**
**NPM 6.13.4 (64 bit)**

I can run `npm install` fine but when I run `npm run build` i get the following error:

```
C:\dev\melloware-git\vis-timeline>npm run build

> vis-timeline@0.0.0-no-version build C:\dev\melloware-git\vis-timeline
> cpy --cwd=types --parents "**/*" "../declarations" && rollup --config rollup.build.js && rollup --config rollup.config.js

[!] AssertionError: There has to be a single entry file (entry-esnext.{js,ts}) for the ESNext build: expected [] to have a length of 1 but got 0
AssertionError: There has to be a single entry file (entry-esnext.{js,ts}) for the ESNext build: expected [] to have a length of 1 but got 0
    at callback (C:\dev\melloware-git\vis-timeline\node_modules\vis-dev-utils\src\module\generate-rollup-configuration\index.ts:410:18)
    at validate (C:\dev\melloware-git\vis-timeline\node_modules\vis-dev-utils\src\module\generate-rollup-configuration\index.ts:152:12)
    at C:\dev\melloware-git\vis-timeline\node_modules\vis-dev-utils\src\module\generate-rollup-configuration\index.ts:405:5
    at Array.map (<anonymous>)
    at Object.generateRollupConfiguration (C:\dev\melloware-git\vis-timeline\node_modules\vis-dev-utils\src\module\generate-rollup-configuration\index.ts:397:53)
    at Object.<anonymous> (C:\dev\melloware-git\vis-timeline\rollup.build.js:10:32)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.require.extensions.<computed> [as .js] (C:\dev\melloware-git\vis-timeline\node_modules\rollup\dist\bin\rollup:1612:20)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at loadConfigFromBundledFile (C:\dev\melloware-git\vis-timeline\node_modules\rollup\dist\bin\rollup:1620:42)
    at getDefaultFromTranspiledConfigFile (C:\dev\melloware-git\vis-timeline\node_modules\rollup\dist\bin\rollup:1605:12)
    at loadConfigFile (C:\dev\melloware-git\vis-timeline\node_modules\rollup\dist\bin\rollup:1583:15)
    at loadAndParseConfigFile (C:\dev\melloware-git\vis-timeline\node_modules\rollup\dist\bin\rollup:1562:21)
```

**Comment by Kaliph** [comment]
I am experiencing the same issue.

**Comment by yotamberk** [comment]
@Thomaash Can I get your urgent help with this? It seems that the latest version of `vis-dev-utils` is crashing `vis-timeline` esnext build. Can you please help with this? 
I don;t quite understand this issue.

Highly appreciated!
